#!/bin/sh
#
# rebuild from source and check that the binary matches the golden version
./build BBUG
split -b 2048 BBUG.bin && rm xab && mv xaa BBUG.bin_trim

../../converters/nascon BBUG.bin_golden BBUG.NAS_golden       -in bin -out nas -org 0 -csum
../../converters/nascon BBUG.bin_trim   BBUG.NAS_trim_rebuilt -in bin -out nas -org 0 -csum
diff BBUG.NAS_golden BBUG.NAS_trim_rebuilt
