#!/bin/sh
#
# rebuild from source and check that the binary matches the golden versions

z80asm -i simon42.asm  -lsimon42.lst  -osimon42.bin
z80asm -i simon44.asm  -lsimon44.lst  -osimon44.bin
z80asm -i simon45s.asm -lsimon45s.lst -osimon45s.bin
z80asm -i simon50.asm  -lsimon50.lst  -osimon50.bin

# check
diff simon42.bin simon42.bin_golden
diff simon44.bin simon44.bin_golden
diff simon45s.bin simon45s.bin_golden
diff simon50.bin simon50.bin_golden
