#!/usr/bin/perl
#
# script to use the z80 disassembler to reverse the SIMON 4.1 MFB ROM
# The ROM is 2Kbytes located at 0xf000 and expects RAM at 0.

use warnings;
use CPU::Z80::Disassembler;

my $file_name = "simon41mfb.bin_golden";
my $addr = 0xf000;
my $file = "simon41mfb_dis.txt";
my $asm_file = "simon41mfb_dis.asm";


$dis = CPU::Z80::Disassembler->new;
$dis->memory->load_file($file_name, $addr);
$dis->write_dump($file);

# mock up stuff for NAS-SYS RST codes

###########################################
# RST 0 - START

###########################################
# RST 8 - RIN

###########################################
# RST 10 - RCAL
## TODO put the actual code thread in here so that it can be followed.
##$dis->memory->poke(0x10, 0xc9);
##$dis->code(0x10);
##$dis->set_call(0x10, \&handle_rcal);

# advance return PC past in-line subroutine code
sub handle_rcal {
    my $addr = $_[1];
    $dis->defb($addr);
    return $addr+1;
}

###########################################
# RST 18 - SCAL
##$dis->memory->poke(0x18, 0xc9);
##$dis->code(0x18);
##$dis->set_call(0x18, \&handle_scal);

# advance return PC past in-line subroutine code
##  sub handle_scal {
##      my $addr = $_[1];
##      $dis->defb($addr);
##      return $addr+1;
##  }

###########################################
# RST 20 - BRKPT

###########################################
# RST 28 - PRS
##  $dis->memory->poke(0x28, 0xc9);
##  $dis->code(0x28);
##  $dis->set_call(0x28, \&handle_prs);

# advance return PC past in-line null-terminated string
sub handle_prs {
    my $ref = $_[0];
    my $addr = $_[1];

    my $start = $addr;
    my $len = 0;
    my $is_string;
    while (1) {
        my $byte = $dis->memory->peek($addr);
        if (($byte > 31) and ($byte < 128)) {
            # printable
            if (($len == 0) or ($is_string==1)) {
                # string, new section, first of section OR
                # string continue existing section
                $len += 1;
                $addr += 1;
                $is_string = 1;
            }
            else {
                # byte -> string change
                if ($gen_label) {
                    $dis->defb($start, $len, $label);
                    $gen_label = 0;
                }
                else {
                    $dis->defb($start, $len);
                }
                $len = 1;
                $is_string = 1;
                $start = $addr;
                $addr += 1;
            }
        }
        else {
            # not printable
            if (($len == 0) or ($is_string==0)) {
                # byte, new section, first of section OR
                # byte continue existing section
                $len += 1;
                $addr += 1;
                $is_string = 0;
            }
            else {
                # string -> byte change
                if ($gen_label) {
                    $dis->defm($start, $len, $label);
                    $gen_label = 0;
                }
                else {
                    $dis->defm($start, $len);
                }
                $len = 1;
                $is_string = 0;
                $start = $addr;
                $addr += 1;
            }
        }
        last if ($byte==0);
    }

    # emit the final section
    if ($len != 0) {
        if ($is_string) {
            if ($gen_label) {
                $dis->defm($start, $len, $label);
            }
            else {
                $dis->defm($start, $len);
            }
        }
        else {
            if ($gen_label) {
                $dis->defb($start, $len, $label);
            }
            else {
                $dis->defb($start, $len);
            }
        }
    }
    return $addr;
}


# Create a message of length $len starting at address $addr and
# using label $label.
# Use defm and defb to report the bytes of the message
# Return the next address
sub msg_by_len {
    my $addr = $_[0];
    my $len = $_[1];
    my $label = $_[2];

    my $start = $addr;
    my $end = $addr + $len; # loop while < $end
    my $gen_label = 1;  # flag
    $len = 0;
    my $is_string;

    # byte new section, first of section
    # byte continue existing section
    # string -> byte change

    while ($addr < $end) {
        my $byte = $dis->memory->peek($addr);
        if (($byte > 31) and ($byte < 128)) {
            # printable
            if (($len == 0) or ($is_string==1)) {
                # string, new section, first of section OR
                # string continue existing section
                $len += 1;
                $addr += 1;
                $is_string = 1;
            }
            else {
                # byte -> string change
                if ($gen_label) {
                    $dis->defb($start, $len, $label);
                    $gen_label = 0;
                }
                else {
                    $dis->defb($start, $len);
                }
                $len = 1;
                $is_string = 1;
                $start = $addr;
                $addr += 1;
            }
        }
        else {
            # not printable
            if (($len == 0) or ($is_string==0)) {
                # byte, new section, first of section OR
                # byte continue existing section
                $len += 1;
                $addr += 1;
                $is_string = 0;
            }
            else {
                # string -> byte change
                if ($gen_label) {
                    $dis->defm($start, $len, $label);
                    $gen_label = 0;
                }
                else {
                    $dis->defm($start, $len);
                }
                $len = 1;
                $is_string = 0;
                $start = $addr;
                $addr += 1;
            }
        }
    }
    # emit the final section
    if ($len != 0) {
        if ($is_string) {
            if ($gen_label) {
                $dis->defm($start, $len, $label);
            }
            else {
                $dis->defm($start, $len);
            }
        }
        else {
            if ($gen_label) {
                $dis->defb($start, $len, $label);
            }
            else {
                $dis->defb($start, $len);
            }
        }
    }
    return $end;
}

###########################################
# RST 30 - ROUT
##$dis->memory->poke(0x30, 0xc9);
##$dis->code(0x30);

###########################################
# RST 38 - RDEL
##$dis->memory->poke(0x38, 0xc9);
##$dis->code(0x38);

###########################################
# NAS-SYS initialisation routine
##$dis->memory->poke(0xd, 0xc9);
##$dis->code(0xd,"STMON");

###########################################
# NAS-SYS entry point
# Never actually come back from here, but
# model it as "ret"
##$dis->memory->poke(0x5, 0xc9);
##$dis->code(0x5,"NAS");

# given a list of addresses, do a $dis->code on each
# of them, with a label of the form X_<addr> where
# <addr> is a 4-digit hex address with leading zeros
sub dis_here {
    while (my $addr = shift @_) {
        my $label = sprintf("X_%04X", $addr);
        $dis->code($addr,$label);
    }
}

# given an address, declare the first as a byte and the next two as a word
# with a label
# and return the next address
# $prefix is the prefix of the label, and $use_addr defines the format
sub dis_tab1 {
    my $prefix = $_[0];
    my $addr = $_[1];
    my $use_addr = $_[2];
    $dis->defb($addr,1);
    $dis->defw($addr+1,1);
    my $ascii = $dis->memory->peek($addr);
    my $val = $dis->memory->peek16u($addr+1);
    my $label;
    if ($use_addr) {
        $label = sprintf("%s_%04X", $prefix, $val);
    }
    else {
        $label = sprintf("%s_CHR%02X", $prefix, $ascii);
    }
    $dis->code($val,$label);
    return $addr+3;
}

# @comments = ("foo", "bar");
# code_com(0x1234, "label", @comments);
#
# gotcha: need all the subsequent commented lines to be marked as code BEFORE this is called
sub code_com {
    my $addr = shift @_;
    my $label = shift @_;

    $dis->code($addr, $label);
    $dis->line_comments($addr, @_);
}


###########################################
# Stuff specific to the code being disassembled

# Commands:


# Workspace:
# 0x5B


$dis->block_comment(0xf000,";;; After reset, the ROM is decoded at 0 and throughout the address map. After the\n;;; first write to port 0xFF, the ROM is only decoded at 0xFXXX. Before that write,\n;;; there must be a jump to 0xFXXX. ROM can be disabled by setting port 0xBC[3]=1\n;;;ports: 0xB4-0xB7 PIO\n;;;        0xB8-0xBF 8250 UART\n;;;        0xFE      Memory mapper\n;;;        0xFF      Page-mode.\n;;; IVC:\n;;;        0xB1      IVC Data (r/w)\n;;;        0xB2      IVC Status (ro)\n;;;        0xB3      IVC Reset (r/w)\n;;; 0x3B-0x5B RP/M Workspace");

# Entry points
$dis->code(0xf000,"COLD");
$dis->code(0xf003,"CHRIN");
$dis->code(0xf006,"CHROUT");
$dis->code(0xf009,"P2HEX");
$dis->code(0xf00c,"P4HEX");
$dis->code(0xf00f,"SPACE");
$dis->code(0xf012,"CRLF");

$dis->code(0xf033,"XCOLD");
$dis->code(0xf3d5,"XCHRIN");
$dis->code(0xf3d8,"XCHROUT");
$dis->code(0xf588,"XP2HEX");
$dis->code(0xf583,"XP4HEX");
$dis->code(0xf5a1,"XSPACE");
$dis->code(0xf59c,"XCRLF");


msg_by_len(0xf015, 16, "MSG1");
msg_by_len(0xf077, 27, "MSG2");
msg_by_len(0xf092, 20, "MSG3");
msg_by_len(0xf0a6, 13, "MSG4");
msg_by_len(0xf0b3, 28, "MSG5");
msg_by_len(0xf461, 31, "MSG6");
msg_by_len(0xf495, 24, "MSG7");
msg_by_len(0xf4ad, 38, "MSG8");
msg_by_len(0xf4d3, 13, "MSG9");
#msg_by_len(0xf534, 29, "MSG10");
#msg_by_len(0xf551, 27, "MSG11");
msg_by_len(0xf560, 10, "MSG12");
msg_by_len(0xf2fd, 3,  "MSG13");
msg_by_len(0xf300, 2,  "MSG14");
msg_by_len(0xf0f4, 27, "MSG15");
msg_by_len(0xf10f, 3,  "MSG16");
msg_by_len(0xf182, 40, "MSG17");
msg_by_len(0xf4e0, 40, "MSG18");
msg_by_len(0xf02f, 4,  "MSG19");
msg_by_len(0xf025, 10,  "MSG20");

@comments = ("reset IVC",
             "",
             "select drive 0/A",
             "count ??of mapper pages to init??",
             "B=?? C= port for MMAP",
             "value?",
             "initialise memory mapper",
             "",
             "",
             "",
             "",
             "continue",
             "",
             "0x64 = 40",
             "value?",
             "page-mode register",
             "",
             "",
             "",
             "",
             "wot??",
             "",
             "",
             "",
             "",
             "",
             "",
             "",
             "e5",
    );
$dis->line_comments(0xf033,@comments);



$dis->code(0xf0cf);

@comments = ("print 0-terminated string at (HL)",
             "??with special treatment of 0x80 and othere?");
code_com(0xf3aa,"PRS", @comments);

$dis->code(0xf0eb);
$dis->code(0xf150);
$dis->code(0xf27f);
$dis->code(0xf282);
$dis->code(0xf285);
$dis->code(0xf288);
$dis->code(0xf28b);
$dis->code(0xf28e);
$dis->code(0xf2d5);

# Where is T(abulate) and what is 8 for?
$dis->code(0xf441,"CMD_A");
$dis->code(0xf56a,"CMD_B");
$dis->code(0xf5f7,"CMD_C");
$dis->code(0xf60a,"CMD_G");
$dis->code(0xf60e,"CMD_F");
$dis->code(0xf625,"CMD_S");
$dis->code(0xf65e,"CMD_O");
$dis->code(0xf672,"CMD_Q");
$dis->code(0xf683,"CMD_D");
$dis->code(0xf6af,"CMD_V");
$dis->code(0xf480,"CMD_8");

$dis->code(0xf428,"INIVC");
$dis->code(0xf3ec,"PUTIVC");




@comments = ("send command in A to FDC then wait then poll status (for completion?)",
             "delay loop count for command acceptance",
             "",
             "wait a little while",
             "read status",
             "completion?",
             "not yet.. loop",
             "done"
    );
code_com(0xf302,"CMD2FDC", @comments);



$dis->defw(0xf25c,13,"BAUDTAB");


$dis->code(0xf321);
$dis->code(0xf37c);
$dis->code(0xf570);


#labels
$dis->code(0xf1aa,"RDSEC0");
$dis->code(0xf1c7,"LDSEC");
$dis->code(0xf1dd,"INITIO");
$dis->code(0xf223,"SERIO");
$dis->code(0xf27f,"JPTAB1");
$dis->code(0xf288,"JPTAB2");
$dis->code(0xf276,"CP92E6");
$dis->code(0xf291,"WOTIO");
$dis->code(0xf296,"CLEAN");
$dis->code(0x00e6,"IOPOLL");
$dis->code(0x00e9,"IOGET");
$dis->code(0x00ec,"IOPUT");
$dis->code(0xf3f6,"PUTSER");
$dis->code(0xf403,"POLIVC");
$dis->code(0xf412,"GETIVC");
$dis->code(0xf430,"POLSER");
$dis->code(0xf435,"GETSER");
$dis->code(0xf55a,"CMDERR");
$dis->code(0xf486,"CMD81");
$dis->code(0xf511,"CMDLOP");
$dis->code(0xf5e1,"GET16");
$dis->code(0xf5ed,"GET16F");

# dead code
$dis->defb(0xf6b5,7);
$dis->code(0xf6bc);
$dis->code(0xf6de);
$dis->code(0xf6f2);


#$dis->defb(0xf700,16);
$dis->defb(0xf710,16);
$dis->defb(0xf720,16);
$dis->defb(0xf730,16);
$dis->defb(0xf740,16);
$dis->defb(0xf750,16);
$dis->defb(0xf760,16);
$dis->defb(0xf770,16);
$dis->defb(0xf780,16);



$dis->defb(0xf790,16);
$dis->defb(0xf7a0,16);
$dis->defb(0xf7b0,16);
$dis->defb(0xf7c0,16);
$dis->defb(0xf7d0,16);
$dis->defb(0xf7e0,16);
$dis->defb(0xf7f0,16);

$dis->code(0xf159);
$dis->code(0xf331);

#msg_by_len(0xf425, 3, "MSG8");

#@comments = ("",
#             "",
#    );
#$dis->line_comments(0xfdb1, @comments);


# This can optimise code and so it may prevent 100% match
# on re-assembly.
##$dis->analyse;

$dis->write_asm($asm_file);
