#!/bin/sh
#
# rebuild from source and check that the binary matches the golden version
./build NASSYS1
split -b 2048 NASSYS1.bin && rm xab && mv xaa NASSYS1.bin_trim

../../converters/nascon NASSYS1.bin_golden NASSYS1.NAS_golden       -in bin -out nas -org 0 -csum
../../converters/nascon NASSYS1.bin_trim   NASSYS1.NAS_trim_rebuilt -in bin -out nas -org 0 -csum
diff NASSYS1.NAS_golden NASSYS1.NAS_trim_rebuilt
