#!/bin/bash
#
# ./image_from_sdcard DEVICE
#
# eg: # sudo ./image_from_sdcard /dev/sdb
#
# Copy 33792 blocks of data from the start of the disk to the file nascom4_sdcard_bp_from.img
# This matches the size of the file created by make_full_sdcard_image
#
# Need sudo to read directly from the image device

dd if=$1  of=nascom4_sdcard_bp_from.img bs=512 seek=0 count=33792
